:noindex:
=== Sichten-Konzept
Mit INTERLIS 2 können neben den eigentlichen Sachobjekten auch Sichten modelliert werden. Sichten sind im Prinzip virtuelle Klassen, deren Instanzen nicht Daten eines eigentlichen Gegenstandes der realen Welt sind, sondern rechnerisch aus anderen Objekten abgeleitet werden.

Eine Sichtdefinition besteht aus folgenden Teilen:

* _Basismengen_ – Von welchen Klassen bzw. Sichten fliessen die Objekte in die Berechnung der Sicht-Objekte ein? Bei Klassen werden jeweils nicht nur die eigentlichen Instanzen herangezogen, sondern auch im Sinne des Polymorphismus alle Instanzen von Erweiterungen. INTERLIS definiert nicht, welche Behälter ein System zum Errechnen einer Sicht berücksichtigen muss.

* _Verknüpfungsvorschrift_ – Wie werden die Basismengen verknüpft? INTERLIS 2 kennt Verbindungen (Join), Vereinigungen (Union), Zusammenfassungen (Aggregation) und Aufschlüsselungen (Inspection) von Unterstrukturen. Mengentheoretisch gesehen bilden Verbindungen das Kreuzprodukt und Vereinigungen die Vereinigungsmenge der Basismengen. Zusammenfassungen erlauben es, Objekte der Basismenge zu einem neuen Sichtobjekt zusammenzufassen, wenn sie definierbare Kriterien erfüllen. Inspektionen von Unterstrukturen ermöglichen es, die Strukturelemente einer Unterstruktur als Menge von Strukturelementen zu sehen. Verbindungen und Zusammenfassungen können auch als virtuelle Assoziationen aufgefasst werden.

* _Selektion_ – Welche errechneten Objekte sollen tatsächlich zur Sicht gehören? INTERLIS erlaubt es, hierfür komplexe Bedingungen anzugeben.
