:noindex:
=== Nutzung von Modellen
Ein INTERLIS-Modell (bzw. INTERLIS-Schema) ist primär eine Verständigungshilfe für Anwender. Die Sprache ist so gestaltet, dass ein Modell leicht von Menschen gelesen werden kann. Dennoch sind INTERLIS-Modelle präzis, eindeutig und ohne Missverständnisse interpretierbar. Die textuelle INTERLIS-Sprache bietet sich daher geradezu an als notwendige Ergänzung der grafischen Beschreibungssprache Unified Modeling Language (UML, www.omg.org/uml).

INTERLIS geht aber noch einen Schritt weiter: Da ein Modell eine formal klar definierte Bedeutung besitzt, ist die Implementation eines Dienstes in einem Computersystem automatisch aus diesem (konzeptionellen) Modell ableitbar. Beispielsweise umfasst INTERLIS einen XML-basierten Transfer-Dienst, dessen Definitionen regelbasiert aus den jeweiligen Modellen erzeugt werden. Die Nutzung der Datenmodellierung in enger Verbindung mit systemneutralen Schnittstellendiensten nennt man den modell-basierten oder den modell-getriebenen Ansatz (siehe «Model-Driven Architecture» von OMG, www.omg.org/mda/).

Modelle können auf gemeinsamen Basiskonzepten aufbauen. Da INTERLIS erlaubt, dies durch die Benutzung von Vererbung und Polymorphismus explizit zu beschreiben, ist jederzeit klar, welche Konzepte gemeinsam und welche jeweils spezifisch sind. Dies ist im Hinblick auf eine angestrebte semantische Interoperabilität von grosser Bedeutung. Beispielsweise kann die Transferdatei einer Gemeinde problemlos von einer übergeordneten Verwaltungseinheit (Kanton, Bund) interpretiert werden, ohne dass sich die Beteiligten dafür auf ein einziges Modell einigen müssten. Es genügt, wenn jede Stufe ihr Modell auf jenem der übergeordneten Einheit aufbaut.

Es ist denkbar und durchaus erwünscht, dass neue Dienste auf der Basis von INTERLIS entwickelt werden. Dies wird erheblich durch einen INTERLIS 2-Compiler erleichtert. Dieses Programm liest und schreibt INTERLIS-Modelle, erlaubt deren Änderung und überprüft, ob Modelle den syntaktischen und semantischen Bedingungen von INTERLIS entsprechen. Dieser Compiler kann – gemäss dem aktuellen INTERLIS-Transferdienst mit XML – unter anderem aus INTERLIS-Modellen automatisch XML-Schema-Dokumente (www.w3.org/XML/Schema) generieren. Damit können die konkreten INTERLIS-XML-Daten durch entsprechende allgemeine XML-Werkzeuge noch breiter genutzt werden. Solange die Nutzungsbedingungen nicht verletzt werden, steht dieser INTERLIS-Compiler zum Erstellen neuer Werkzeuge zur Verfügung.
